name: rff-fair2.1
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - flake8
  - isort
  - jupyter
  - nbstripout
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pyam>=1.7
  - python-dotenv
  - scipy
  - tqdm
  - pip
  - pip:
    - fair==2.1.0
    - silicone
