name: rff-fair2.1
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - nbstripout
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pooch
  - scipy
  - tqdm
  - pip
  - pip:
    # install a local copy of FaIR2.1 (ensure that repo is up to date)
    - -e ../fair2.1-calibrate
