name: rff-fair2.1
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - nbstripout
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pooch
  - scipy
  - tqdm
  - pip
  - pip:
    - fair==2.1.0
    - silicone
